zookeeper:
  image: jplock/zookeeper
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"

mesos-master:
  image: redjack/mesos-master
  environment:
    MESOS_QUORUM=1
    MESOS_LOG_DIR=/var/log
    MESOS_WORK_DIR=/tmp
    MESOS_ZK=zk://zookeeper:2181/mesos
  links:
    - zookeeper:zookeeper
